// Code generated by MockGen. DO NOT EDIT.
// Source: geraldaddo.com/live-voting-system/domain/election (interfaces: ElectionRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_election_repo.go -package=mocks . ElectionRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	election "geraldaddo.com/live-voting-system/domain/election"
	gomock "go.uber.org/mock/gomock"
)

// MockElectionRepository is a mock of ElectionRepository interface.
type MockElectionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockElectionRepositoryMockRecorder
	isgomock struct{}
}

// MockElectionRepositoryMockRecorder is the mock recorder for MockElectionRepository.
type MockElectionRepositoryMockRecorder struct {
	mock *MockElectionRepository
}

// NewMockElectionRepository creates a new mock instance.
func NewMockElectionRepository(ctrl *gomock.Controller) *MockElectionRepository {
	mock := &MockElectionRepository{ctrl: ctrl}
	mock.recorder = &MockElectionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockElectionRepository) EXPECT() *MockElectionRepositoryMockRecorder {
	return m.recorder
}

// GetAllWithFilters mocks base method.
func (m *MockElectionRepository) GetAllWithFilters(ctx context.Context, params election.ElectionQueryParams) ([]election.Election, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllWithFilters", ctx, params)
	ret0, _ := ret[0].([]election.Election)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllWithFilters indicates an expected call of GetAllWithFilters.
func (mr *MockElectionRepositoryMockRecorder) GetAllWithFilters(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllWithFilters", reflect.TypeOf((*MockElectionRepository)(nil).GetAllWithFilters), ctx, params)
}

// GetById mocks base method.
func (m *MockElectionRepository) GetById(ctx context.Context, id string) (*election.Election, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(*election.Election)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockElectionRepositoryMockRecorder) GetById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockElectionRepository)(nil).GetById), ctx, id)
}

// Save mocks base method.
func (m *MockElectionRepository) Save(ctx context.Context, entity *election.Election) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockElectionRepositoryMockRecorder) Save(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockElectionRepository)(nil).Save), ctx, entity)
}

// UpdateOne mocks base method.
func (m *MockElectionRepository) UpdateOne(ctx context.Context, id string, entity *election.Election) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOne", ctx, id, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOne indicates an expected call of UpdateOne.
func (mr *MockElectionRepositoryMockRecorder) UpdateOne(ctx, id, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOne", reflect.TypeOf((*MockElectionRepository)(nil).UpdateOne), ctx, id, entity)
}
